# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/gtel3g/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/gtel3g

PRODUCT_COPY_FILES += \
    vendor/samsung/gtel3g/proprietary/bin/at_distributor:$(TARGET_COPY_OUT_SYSTEM)/bin/at_distributor \
    vendor/samsung/gtel3g/proprietary/bin/engpc:$(TARGET_COPY_OUT_SYSTEM)/bin/engpc \
    vendor/samsung/gtel3g/proprietary/bin/ext_data.sh:$(TARGET_COPY_OUT_SYSTEM)/bin/ext_data.sh \
    vendor/samsung/gtel3g/proprietary/bin/ext_kill.sh:$(TARGET_COPY_OUT_SYSTEM)/bin/ext_kill.sh \
    vendor/samsung/gtel3g/proprietary/bin/ext_symlink.sh:$(TARGET_COPY_OUT_SYSTEM)/bin/ext_symlink.sh \
    vendor/samsung/gtel3g/proprietary/bin/gps.cer:$(TARGET_COPY_OUT_SYSTEM)/bin/gps.cer \
    vendor/samsung/gtel3g/proprietary/bin/gpsd:$(TARGET_COPY_OUT_SYSTEM)/bin/gpsd \
    vendor/samsung/gtel3g/proprietary/bin/macloader:$(TARGET_COPY_OUT_SYSTEM)/bin/macloader \
    vendor/samsung/gtel3g/proprietary/bin/modemd:$(TARGET_COPY_OUT_SYSTEM)/bin/modemd \
    vendor/samsung/gtel3g/proprietary/bin/nvitemd:$(TARGET_COPY_OUT_SYSTEM)/bin/nvitemd \
    vendor/samsung/gtel3g/proprietary/bin/phoneserver:$(TARGET_COPY_OUT_SYSTEM)/bin/phoneserver \
    vendor/samsung/gtel3g/proprietary/bin/refnotify:$(TARGET_COPY_OUT_SYSTEM)/bin/refnotify \
    vendor/samsung/gtel3g/proprietary/bin/rild:$(TARGET_COPY_OUT_SYSTEM)/bin/rild \
    vendor/samsung/gtel3g/proprietary/etc/wifi/bcmdhd_apsta.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/gtel3g/proprietary/etc/wifi/bcmdhd_mfg.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/gtel3g/proprietary/etc/wifi/bcmdhd_sta.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/gtel3g/proprietary/etc/wifi/nvram_mfg.txt:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/nvram_mfg.txt \
    vendor/samsung/gtel3g/proprietary/etc/wifi/nvram_net.txt:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/nvram_net.txt \
    vendor/samsung/gtel3g/proprietary/lib/egl/libGLES_mali.so:$(TARGET_COPY_OUT_SYSTEM)/lib/egl/libGLES_mali.so \
    vendor/samsung/gtel3g/proprietary/lib/hw/camera.sc8830.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/camera.sc8830.so \
    vendor/samsung/gtel3g/proprietary/lib/hw/gps.default.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/gps.default.so \
    vendor/samsung/gtel3g/proprietary/lib/hw/gralloc.sc8830.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/gralloc.sc8830.so \
    vendor/samsung/gtel3g/proprietary/lib/hw/hwcomposer.sc8830.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/hwcomposer.sc8830.so \
    vendor/samsung/gtel3g/proprietary/lib/hw/sensors.sc8830.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/sensors.sc8830.so \
    vendor/samsung/gtel3g/proprietary/lib/hw/sprd_gsp.sc8830.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/sprd_gsp.sc8830.so \
    vendor/samsung/gtel3g/proprietary/lib/libatchannel.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libatchannel.so \
    vendor/samsung/gtel3g/proprietary/lib/libatparser.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libatparser.so \
    vendor/samsung/gtel3g/proprietary/lib/libboost.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libboost.so \
    vendor/samsung/gtel3g/proprietary/lib/libfactoryutil.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libfactoryutil.so \
    vendor/samsung/gtel3g/proprietary/lib/libisp.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libisp.so \
    vendor/samsung/gtel3g/proprietary/lib/libmorpho_easy_hdr.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmorpho_easy_hdr.so \
    vendor/samsung/gtel3g/proprietary/lib/libomission_avoidance.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libomission_avoidance.so \
    vendor/samsung/gtel3g/proprietary/lib/libomx_aacdec_sprd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libomx_aacdec_sprd.so \
    vendor/samsung/gtel3g/proprietary/lib/libomx_avcdec_hw_sprd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libomx_avcdec_hw_sprd.so \
    vendor/samsung/gtel3g/proprietary/lib/libomx_avcenc_hw_sprd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libomx_avcenc_hw_sprd.so \
    vendor/samsung/gtel3g/proprietary/lib/libomx_m4vh263dec_hw_sprd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libomx_m4vh263dec_hw_sprd.so \
    vendor/samsung/gtel3g/proprietary/lib/libomx_m4vh263enc_hw_sprd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libomx_m4vh263enc_hw_sprd.so \
    vendor/samsung/gtel3g/proprietary/lib/libomx_mp3dec_sprd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libomx_mp3dec_sprd.so \
    vendor/samsung/gtel3g/proprietary/lib/libomx_vpxdec_hw_sprd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libomx_vpxdec_hw_sprd.so \
    vendor/samsung/gtel3g/proprietary/lib/libreference-ril_sp.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libreference-ril_sp.so \
    vendor/samsung/gtel3g/proprietary/lib/libril.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libril.so \
    vendor/samsung/gtel3g/proprietary/lib/librilutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/librilutils.so \
    vendor/samsung/gtel3g/proprietary/lib/libsecnativefeature.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsecnativefeature.so \
    vendor/samsung/gtel3g/proprietary/lib/libsecril-client.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsecril-client.so \
    vendor/samsung/gtel3g/proprietary/lib/libsprd_agps_agent.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsprd_agps_agent.so \
    vendor/samsung/gtel3g/proprietary/lib/libuvdenoise.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libuvdenoise.so \
    vendor/samsung/gtel3g/proprietary/vendor/firmware/BCM43430A1_001.002.009.0022.0000_Samsung_TabE_SM-T561_TEST_ONLY.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/BCM43430A1_001.002.009.0022.0000_Samsung_TabE_SM-T561_TEST_ONLY.hcd \
    vendor/samsung/gtel3g/proprietary/vendor/firmware/vbc_eq:$(TARGET_COPY_OUT_VENDOR)/firmware/vbc_eq
